Repository supreme-gg-gg/instagram-cli, pull requests merged in 2025-03, with the labels that each got.

#45 UEP 1.2.10
  instagram/__init__.py
  instagram/api/__init__.py
  instagram/api/direct_messages.py
  instagram/chat.py
  instagram/cli.py
  pyproject.toml
Labels: bug, enhancement, ^^

#54 IEP 3
  README.md
  instagram/__init__.py
  instagram/api/__init__.py
  instagram/api/direct_messages.py
  instagram/api/utils.py
  instagram/chat.py
  instagram/chat_ui/components/chat_window.py
  instagram/chat_ui/components/input_box.py
  instagram/chat_ui/components/status_bar.py
  instagram/chat_ui/interface/chat_interface.py
  instagram/chat_ui/interface/chat_menu.py
  instagram/chat_ui/utils/chat_commands.py
  instagram/chat_ui/utils/types.py
  instagram/cli.py
  instagram/client.py
  pyproject.toml
Labels: bug, enhancement

#57 [UEP] 1.3.1: ChatMenu refactor + browsing, chat UI bug fix
  CONTRIBUTING.md
  README.md
  instagram/__init__.py
  instagram/api/direct_messages.py
  instagram/api/utils.py
  instagram/chat.py
  instagram/chat_ui/__init__.py
  instagram/chat_ui/interface/chat_interface.py
  instagram/chat_ui/interface/chat_menu.py
  instagram/chat_ui/utils/chat_commands.py
  instagram/chat_ui/utils/types.py
  instagram/cli.py
  pyproject.toml
Labels: bug, ^^^
