Repository supreme-gg-gg/instagram-cli, pull requests merged in 2025-02, with the labels that each got.

#9 Chat Commands and Chat UI Patches
  instagram/__init__.py
  instagram/analytics.py
  instagram/api/__init__.py
  instagram/api/analytics.py
  instagram/api/direct_messages.py
  instagram/cache.py
  instagram/chat_commands.py
  instagram/chat_ui.py
  instagram/cli.py
  instagram/client.py
  instagram/commands.py
  instagram/configs.py
  requirements.txt
  setup.py
Labels: enhancement

#22 UEP 2.1
  README.md
  instagram/api/analytics.py
  instagram/api/direct_messages.py
  instagram/chat_commands.py
  instagram/chat_ui.py
  instagram/cli.py
  instagram/commands.py
Labels: bug, enhancement, ^^^

#29 IEP 2.2
  .gitignore
  docs/beta-testing.md
  instagram/__init__.py
  instagram/api/__init__.py
  instagram/api/direct_messages.py
  instagram/api/scheduler.py
  instagram/api/utils.py
  instagram/auth.py
  instagram/chat.py
  instagram/chat_ui.py
  instagram/chat_ui/__init__.py
  instagram/chat_ui/components/__init__.py
  instagram/chat_ui/components/chat_window.py
  instagram/chat_ui/components/input_box.py
  instagram/chat_ui/components/status_bar.py
  instagram/chat_ui/interface/__init__.py
  instagram/chat_ui/interface/chat_interface.py
  instagram/chat_ui/interface/chat_menu.py
  instagram/chat_ui/utils/__init__.py
  instagram/chat_ui/utils/chat_commands.py
  instagram/chat_ui/utils/commands.py
  instagram/chat_ui/utils/loading.py
  instagram/chat_ui/utils/types.py
  instagram/cli.py
  instagram/client.py
  instagram/commands.py
  instagram/configs.py
  requirements.txt
  setup.py
Labels: bug, documentation, enhancement, ^^
